version: '3.6'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example    
    ports:
      - "5060:27017"
    networks:
      - crawler-network
      
  crawler-fe:
    image: andreyley/crawler-fe:1.0.0
    container_name: crawler-fe

    ports:
      - "3000:3000"
    # volumes:
      # - '.:/app'
      # - '/app/node_modules'
    networks:
      - crawler-network
    depends_on:
      - crawler-be
    stdin_open: true
    restart: always
  
  crawler-be:
    image: andreyley/crawler-be:1.0.0
    container_name: crawler-be
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "5050:5050"
    links:
      - mongo
    networks:
      - crawler-network
    depends_on:
      - mongo
    restart: always
    


      
networks:
  crawler-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24        
  
        